### ISSUE TITLE
슬랙으로 알람이 오지 않아요!

### ISSUE THREAD

**Issue by devssun** [techinpark/today-devblog-bot#2]
README에 작성해주신 대로 적용해봤지만 알람이 오지 않습니다..
제 레포에 Actions로 들어가면 아무것도 없던데, 그게 맞나요? 혹시 Actions에 뭔갈 추가해줘야하나요?

**Comment by retheviper** [comment]
저도 마찬가지 상황입니다. fork한 리포지토리이기에 Actions를 적용하지 않았다는 알림이 있는 거로 봐서는 추가적인 조치를 뭔가 취해야 할 것 같습니다.

**Comment by retheviper** [comment]
자답입니다. fork한 리포지토리 내에서 새로 Actions 작성을 선택한 뒤, `.github/workflows/node.yml` 파일의 내용을 붙여넣기 하면 됩니다.

**Comment by techinpark** [comment]
@devssun 늦게 답변드려서 죄송합니다 @retheviper 님께서 하신방법대로 하시면 될것 같네요 😄

**Comment by devssun** [comment]
감사합니다. 확인해보갰습니다 😃
