### ISSUE TITLE
Mattermost 지원

### ISSUE THREAD

**Issue by retheviper** [techinpark/today-devblog-bot#3]
`app.ts`의 이하의 조건문 떄문에 Mattermost에서는 webhook 설정을 해도 JSON이 전송이 안 됩니다.

```ts
if(url.includes('hooks.slack.com')) {
```

저같은 경우 별도 도메인에 설치형으로 Mattermost를 사용하고 있는 환경인데, 이러한 경우 URL에 `slack.com`이 들어가지 않습니다.

코드를 아래와 같이 바꿨을 경우 전송이 문제없이 되는 것을 확인했습니다.

```ts
if(url.includes('hooks')) {
```

문제가 되지 않는다면 후자의 코드로 수정하는 것이 Slack과 Mattermost 양쪽을 다 지원하게 되는 것이니 좋지 않을까 합니다만 어떠실까요.

**Comment by techinpark** [comment]
@retheviper 좋은 의견 감사드립니다. 원래 의도는 슬랙에서만 동작하는 봇을 만드는것이었는데 말씀하신 방향으로 수정을 하면 `Mattermost` 에서도 사용을 할 수가 있게 되겠네요!  말씀해주신 부분을 참고해서 조건을 하나 더 추가하는것이 좋을것 같아요 👍

**Comment by retheviper** [comment]
답변 감사합니다. PR 날려드리고 싶은데, dependecy 업데이트나 Github Actions 관련 설정 때문에 커밋이 뒤죽박죽 섞여 있어서 제가 PR을 올려드리기가 애매하네요.
